// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authentication.Data;

public partial class ComapanyRole
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public string RoleKey { get; set; }

    public string RoleName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastEditedDate { get; set; }

    public long? CreatedId { get; set; }

    public long? EditedId { get; set; }

    public bool? Active { get; set; }

    public virtual Company Company { get; set; }
}