// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authentication.Data;

public partial class DoctorInfo
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public long ContactId { get; set; }

    public long SpecialityId { get; set; }

    public long EducationId { get; set; }

    public long LanguageId { get; set; }

    public long Experience { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastEditedDate { get; set; }

    public long? CreatedId { get; set; }

    public long? EditedId { get; set; }

    public bool? Active { get; set; }

    public virtual Company Company { get; set; }

    public virtual Contact Contact { get; set; }
}