// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCare.Data;

public partial class Company
{
    public long Id { get; set; }

    public string CompanyName { get; set; }

    public long CompanyTypeId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastEditedDate { get; set; }

    public long? CreatedId { get; set; }

    public long? EditedId { get; set; }

    public bool? Active { get; set; }

    public string CompanyLogo { get; set; }

    public virtual ICollection<ComapanyRole> ComapanyRoles { get; set; } = new List<ComapanyRole>();

    public virtual ICollection<CompanyTaggedContact> CompanyTaggedContacts { get; set; } = new List<CompanyTaggedContact>();

    public virtual ICollection<DoctorInfo> DoctorInfos { get; set; } = new List<DoctorInfo>();

    public virtual ICollection<Education> Educations { get; set; } = new List<Education>();

    public virtual ICollection<Language> Languages { get; set; } = new List<Language>();

    public virtual ICollection<Lookup> Lookups { get; set; } = new List<Lookup>();

    public virtual ICollection<Speciality> Specialities { get; set; } = new List<Speciality>();
}