// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCare.Data;

public partial class Contact
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Mobile { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastEditedDate { get; set; }

    public long? CreatedId { get; set; }

    public long? EditedId { get; set; }

    public bool? Active { get; set; }

    public long Age { get; set; }

    public long GenderId { get; set; }

    public string ProfileId { get; set; }

    public virtual ICollection<CompanyTaggedContact> CompanyTaggedContacts { get; set; } = new List<CompanyTaggedContact>();

    public virtual ICollection<ContactAddress> ContactAddresses { get; set; } = new List<ContactAddress>();

    public virtual ICollection<DoctorInfo> DoctorInfos { get; set; } = new List<DoctorInfo>();
}