// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCare.Data;

public partial class ContactAddress
{
    public long Id { get; set; }

    public long ContactId { get; set; }

    public string Address { get; set; }

    public long CityId { get; set; }

    public long StateId { get; set; }

    public string PinCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastEditedDate { get; set; }

    public long? CreatedId { get; set; }

    public long? EditedId { get; set; }

    public bool? Active { get; set; }

    public long CountryId { get; set; }

    public virtual Contact Contact { get; set; }
}