// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HealthCare.Data;

public partial class HealthCareContext : DbContext
{
    public HealthCareContext(DbContextOptions<HealthCareContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ComapanyRole> ComapanyRoles { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<CompanyTaggedContact> CompanyTaggedContacts { get; set; }

    public virtual DbSet<CompanyType> CompanyTypes { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<ContactAddress> ContactAddresses { get; set; }

    public virtual DbSet<DoctorInfo> DoctorInfos { get; set; }

    public virtual DbSet<Education> Educations { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Lookup> Lookups { get; set; }

    public virtual DbSet<Speciality> Specialities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ComapanyRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comapany__3214EC079CB96631");

            entity.ToTable("ComapanyRole", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.RoleKey)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);

            entity.HasOne(d => d.Company).WithMany(p => p.ComapanyRoles)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ComapanyR__Compa__6D0D32F4");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Company__3214EC07A902587F");

            entity.ToTable("Company", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CompanyLogo)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
        });

        modelBuilder.Entity<CompanyTaggedContact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CompanyT__3214EC07D8DB00D5");

            entity.ToTable("CompanyTaggedContact", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");

            entity.HasOne(d => d.Company).WithMany(p => p.CompanyTaggedContacts)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CompanyTa__Compa__70DDC3D8");

            entity.HasOne(d => d.Contact).WithMany(p => p.CompanyTaggedContacts)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CompanyTa__Conta__71D1E811");
        });

        modelBuilder.Entity<CompanyType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CompanyT__3214EC0727F95459");

            entity.ToTable("CompanyType", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CompanyType1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CompanyType");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
        });

        modelBuilder.Entity<Contact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contact__3214EC07B229C07F");

            entity.ToTable("Contact", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Mobile)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.ProfileId)
                .HasMaxLength(2000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ContactAddress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContactA__3214EC07D7A5A429");

            entity.ToTable("ContactAddress", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(120);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.PinCode)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.HasOne(d => d.Contact).WithMany(p => p.ContactAddresses)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ContactAd__Conta__5FB337D6");
        });

        modelBuilder.Entity<DoctorInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DoctorIn__3214EC07A4514235");

            entity.ToTable("DoctorInfo", "Doctor");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.RegId)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.Company).WithMany(p => p.DoctorInfos)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DoctorInf__Compa__17036CC0");

            entity.HasOne(d => d.Contact).WithMany(p => p.DoctorInfos)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DoctorInf__Conta__17F790F9");
        });

        modelBuilder.Entity<Education>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Educatio__3214EC07C44D766C");

            entity.ToTable("Education", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.Ebinary).HasColumnName("EBinary");
            entity.Property(e => e.Education1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Education");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");

            entity.HasOne(d => d.Company).WithMany(p => p.Educations)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Education__Compa__236943A5");
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Language__3214EC077EA1C43F");

            entity.ToTable("Languages", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.Language1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Language");
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.Lbinary).HasColumnName("LBinary");

            entity.HasOne(d => d.Company).WithMany(p => p.Languages)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Languages__Compa__1F98B2C1");
        });

        modelBuilder.Entity<Lookup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lookup__3214EC073547452B");

            entity.ToTable("Lookup", "Core");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);

            entity.HasOne(d => d.Company).WithMany(p => p.Lookups)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Lookup__CompanyI__66603565");
        });

        modelBuilder.Entity<Speciality>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Speciali__3214EC076893681E");

            entity.ToTable("Speciality", "Doctor");

            entity.Property(e => e.Active).HasColumnName("_Active");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("_CreatedDate");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.LastEditedDate)
                .HasColumnType("datetime")
                .HasColumnName("_LastEditedDate");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(70)
                .IsUnicode(false);
            entity.Property(e => e.Sbinary).HasColumnName("SBinary");

            entity.HasOne(d => d.Company).WithMany(p => p.Specialities)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Specialit__Compa__07C12930");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}